export interface Beverage {
  id: number;
  name: string;
  category: string;
  price: number;
  volume?: string;
  alcohol?: string;
  description?: string;
}

export const beverages: Beverage[] = [
  // ESTATHE E ACQUA
  {
    id: 1,
    name: "ESTATHE' PESCA",
    category: "bevande",
    price: 3.0,
    volume: "VETRO 250 ML",
  },
  {
    id: 2,
    name: "ESTATHE' LIMONE",
    category: "bevande",
    price: 3.0,
    volume: "VETRO 250 ML",
  },
  {
    id: 3,
    name: "ACQUA NATURALE",
    category: "bevande",
    price: 2.5,
    volume: "VETRO 75 CL",
  },
  {
    id: 4,
    name: "ACQUA LETE",
    category: "bevande",
    price: 2.5,
    volume: "VETRO 75 CL",
  },
  {
    id: 5,
    name: "ACQUA NATURALE",
    category: "bevande",
    price: 1.5,
    volume: "PLASTICA 50 CL",
  },
  {
    id: 6,
    name: "ACQUA LETE",
    category: "bevande",
    price: 1.5,
    volume: "PLASTICA 50 CL",
  },
  {
    id: 7,
    name: "COCA COLA, COCA ZERO, FANTA, SPRITE",
    category: "bevande",
    price: 2.5,
    volume: "VETRO 33 CL",
  },
  {
    id: 8,
    name: "CHINOTTO",
    category: "bevande",
    price: 2.5,
    volume: "LATTINA 33 CL",
  },
  {
    id: 9,
    name: "ACQUA TONICA, LEMON SODA",
    category: "bevande",
    price: 2.5,
    volume: "VETRO",
  },

  // BIRRE ALLA SPINA
  {
    id: 10,
    name: "CARLSBERG PILSNER",
    category: "birre alla spina",
    price: 3.5,
    volume: "0,25 CL",
    alcohol: "5%",
  },
  {
    id: 11,
    name: "CARLSBERG PILSNER",
    category: "birre alla spina",
    price: 6.0,
    volume: "0,50 CL",
    alcohol: "5%",
  },
  {
    id: 12,
    name: "CARLSBERG PILSNER",
    category: "birre alla spina",
    price: 12.0,
    volume: "1 LT",
    alcohol: "5%",
  },

  {
    id: 13,
    name: "CARLSBERG SPECIAL BREW",
    category: "birre alla spina",
    price: 4.0,
    volume: "0,25 CL",
    alcohol: "9%",
  },
  {
    id: 14,
    name: "CARLSBERG SPECIAL BREW",
    category: "birre alla spina",
    price: 7.0,
    volume: "0,50 CL",
    alcohol: "9%",
  },
  {
    id: 15,
    name: "CARLSBERG SPECIAL BREW",
    category: "birre alla spina",
    price: 14.0,
    volume: "1 LT",
    alcohol: "9%",
  },

  {
    id: 16,
    name: "GRIMBERGEN DOUBLE",
    category: "birre alla spina",
    price: 4.5,
    volume: "0,25 CL",
    alcohol: "6,5%",
  },
  {
    id: 17,
    name: "GRIMBERGEN DOUBLE",
    category: "birre alla spina",
    price: 6.5,
    volume: "0,50 CL",
    alcohol: "6,5%",
  },
  {
    id: 18,
    name: "GRIMBERGEN DOUBLE",
    category: "birre alla spina",
    price: 13.0,
    volume: "1 LT",
    alcohol: "6,5%",
  },

  {
    id: 19,
    name: "GRIMBERGEN TRIPLE",
    category: "birre alla spina",
    price: 4.5,
    volume: "0,25 CL",
    alcohol: "8%",
  },
  {
    id: 20,
    name: "GRIMBERGEN TRIPLE",
    category: "birre alla spina",
    price: 6.5,
    volume: "0,50 CL",
    alcohol: "8%",
  },
  {
    id: 21,
    name: "GRIMBERGEN TRIPLE",
    category: "birre alla spina",
    price: 13.0,
    volume: "1 LT",
    alcohol: "8%",
  },

  {
    id: 22,
    name: "GRIMBERGEN BLANCHE",
    category: "birre alla spina",
    price: 4.5,
    volume: "0,25 CL",
    alcohol: "6,7%",
  },
  {
    id: 23,
    name: "GRIMBERGEN BLANCHE",
    category: "birre alla spina",
    price: 6.5,
    volume: "0,50 CL",
    alcohol: "6,7%",
  },
  {
    id: 24,
    name: "GRIMBERGEN BLANCHE",
    category: "birre alla spina",
    price: 13.0,
    volume: "1 LT",
    alcohol: "6,7%",
  },

  {
    id: 25,
    name: "GRIMBERGEN BLONDE",
    category: "birre alla spina",
    price: 4.5,
    volume: "0,25 CL",
    alcohol: "6,7%",
  },
  {
    id: 26,
    name: "GRIMBERGEN BLONDE",
    category: "birre alla spina",
    price: 6.5,
    volume: "0,50 CL",
    alcohol: "6,7%",
  },
  {
    id: 27,
    name: "GRIMBERGEN BLONDE",
    category: "birre alla spina",
    price: 13.0,
    volume: "1 LT",
    alcohol: "6,7%",
  },

  // BIRRE SENZA GLUTINE
  {
    id: 28,
    name: "PEDAVENA",
    category: "birre senza glutine",
    price: 5.0,
    volume: "0,33 CL",
    alcohol: "4,8%",
  },
  {
    id: 29,
    name: "PERONI",
    category: "birre senza glutine",
    price: 5.0,
    volume: "0,33 CL",
    alcohol: "4,7%",
  },
  {
    id: 30,
    name: "DAURA",
    category: "birre senza glutine",
    price: 5.0,
    volume: "0,33 CL",
    alcohol: "5,4%",
  },
  {
    id: 31,
    name: "SANMIGUEL",
    category: "birre senza glutine",
    price: 5.0,
    volume: "0,33 CL",
    alcohol: "5,4%",
  },

  // BIRRE IN BOTTIGLIA CONSIGLIATE
  {
    id: 32,
    name: "GöLLER RAUCHBIER AFFUMICATA AL BACON",
    category: "birre in bottiglia",
    price: 7.0,
    volume: "0,50 CL",
    alcohol: "4,9%",
    description: "Birra corposa e speziata con leggero aroma di affumicato.",
  },
  {
    id: 33,
    name: "BIRRA MESSINA CRISTALLI DI SALE",
    category: "birre in bottiglia",
    price: 6.0,
    volume: "0,50 CL",
    alcohol: "5%",
  },
  {
    id: 34,
    name: "BIRRA MESSINA CRISTALLI DI SALE",
    category: "birre in bottiglia",
    price: 4.5,
    volume: "0,33 CL",
    alcohol: "5%",
  },
  {
    id: 35,
    name: "PERONI AL LIMONE",
    category: "birre in bottiglia",
    price: 4.5,
    volume: "0,33 CL",
    alcohol: "2%",
  },
  {
    id: 36,
    name: "CERES IPA",
    category: "birre in bottiglia",
    price: 4.0,
    volume: "0,33 CL",
    alcohol: "5,7%",
  },
  {
    id: 37,
    name: "CERES",
    category: "birre in bottiglia",
    price: 3.5,
    volume: "0,33 CL",
    alcohol: "7,7%",
  },
  {
    id: 38,
    name: "ERDINGER PIKANTUS",
    category: "birre in bottiglia",
    price: 5.0,
    volume: "0,50 CL",
    alcohol: "7,3%",
  },
  {
    id: 39,
    name: "ERDINGER WEISEE",
    category: "birre in bottiglia",
    price: 5.0,
    volume: "0,50 CL",
    alcohol: "5,3%",
  },
  {
    id: 40,
    name: "DESPERADOS",
    category: "birre in bottiglia",
    price: 3.5,
    volume: "0,33 CL",
    alcohol: "5,9%",
  },
  {
    id: 41,
    name: "CORONA",
    category: "birre in bottiglia",
    price: 4.0,
    volume: "0,35 CL",
    alcohol: "4,5%",
  },
  {
    id: 42,
    name: "TENNET'S",
    category: "birre in bottiglia",
    price: 3.5,
    volume: "0,33 CL",
    alcohol: "9%",
  },
  {
    id: 43,
    name: "HEINEKEN",
    category: "birre in bottiglia",
    price: 3.0,
    volume: "0,33 CL",
    alcohol: "5%",
  },

  // VINI ROSSI
  {
    id: 44,
    name: "MARIA COSTANZA (BIO)",
    category: "vini rossi",
    price: 40.0,
    volume: "750 ML",
    alcohol: "14,5%",
    description: "Cantina: Milazzo, Uve: Nero d'Avola, Regione: Sicilia",
  },
  {
    id: 45,
    name: "PRINCIPI DI BUTERA AMIRA NERO D'AVOLA D.O.C.",
    category: "vini rossi",
    price: 22.0,
    volume: "750 ML",
    alcohol: "13,5%",
  },
  {
    id: 46,
    name: "PRINCIPI DI BUTERA AMIRA SYRAH D.O.C.",
    category: "vini rossi",
    price: 22.0,
    volume: "750 ML",
    alcohol: "14%",
  },
  {
    id: 47,
    name: "FINA SYRAH",
    category: "vini rossi",
    price: 23.0,
    volume: "750 ML",
    alcohol: "14%",
  },
  {
    id: 48,
    name: "FINA NERO D'AVOLA (BIO)",
    category: "vini rossi",
    price: 23.0,
    volume: "750 ML",
    alcohol: "13,5%",
  },
  {
    id: 49,
    name: "FINA PERRICONE",
    category: "vini rossi",
    price: 23.0,
    volume: "750 ML",
    alcohol: "13,5%",
  },
  {
    id: 50,
    name: "GORGHI TONDI DUME' (BIO)",
    category: "vini rossi",
    price: 22.0,
    volume: "750 ML",
    alcohol: "13%",
  },
  {
    id: 51,
    name: "GORGHI TONDI SPASSOSO",
    category: "vini rossi",
    price: 22.0,
    volume: "750 ML",
    alcohol: "14%",
  },
  {
    id: 52,
    name: "MURGO LAPILLI",
    category: "vini rossi",
    price: 25.0,
    volume: "750 ML",
    alcohol: "14%",
  },
  {
    id: 53,
    name: "MURGO ETNA ROSSO D.O.C.",
    category: "vini rossi",
    price: 25.0,
    volume: "750 ML",
    alcohol: "13,5%",
  },
  {
    id: 54,
    name: "FIRRIATO BAYAMORE",
    category: "vini rossi",
    price: 22.0,
    volume: "750 ML",
    alcohol: "14%",
  },

  // VINI BIANCHI E BOLLICINE
  {
    id: 55,
    name: "FIRRIATO CHARME (FRIZZANTE)",
    category: "vini bianchi e bollicine",
    price: 23.0,
    volume: "750 ML",
    alcohol: "12%",
  },
  {
    id: 56,
    name: "PRINCIPI DI BUTERA NERO LUCE (BRUT)",
    category: "vini bianchi e bollicine",
    price: 25.0,
    volume: "750 ML",
    alcohol: "12%",
  },
  {
    id: 57,
    name: "VILLA SANDI VALDOBBIADENE PROSECCO D.O.C.G.",
    category: "vini bianchi e bollicine",
    price: 22.0,
    volume: "750 ML",
    alcohol: "11%",
  },
  {
    id: 58,
    name: "VILLA SANDI DOLCE SANDI SPUMANTE DOLCE",
    category: "vini bianchi e bollicine",
    price: 22.0,
    volume: "750 ML",
    alcohol: "7%",
  },
  {
    id: 59,
    name: "MILAZZO BIANCO DI NERA (FRIZZANTE BIO)",
    category: "vini bianchi e bollicine",
    price: 30.0,
    volume: "750 ML",
    alcohol: "12%",
  },
  {
    id: 60,
    name: "MILAZZO MARIA COSTANZA (BIO)",
    category: "vini bianchi e bollicine",
    price: 35.0,
    volume: "750 ML",
    alcohol: "13%",
  },
  {
    id: 61,
    name: "GORGHI TONDI BABBIO (BIO FRIZZANTE)",
    category: "vini bianchi e bollicine",
    price: 20.0,
    volume: "750 ML",
    alcohol: "11,5%",
  },
  {
    id: 62,
    name: "GORGHI TONDI MARAMEO",
    category: "vini bianchi e bollicine",
    price: 20.0,
    volume: "750 ML",
    alcohol: "12%",
  },
  {
    id: 63,
    name: "FINA KIKE",
    category: "vini bianchi e bollicine",
    price: 25.0,
    volume: "750 ML",
    alcohol: "13,5%",
  },
];
