export interface Dough {
  name: string;
  price: number;
}

export interface Drink {
  id: number;
  name: string;
  category: string;
  price: number;
  ingredients: string[];
  chefRecommended?: boolean;
  doughs?: Dough[]; // opzionale, così i drink possono avere [] o non averlo
}

export const drinkItems: Drink[] = [
  {
    id: 1,
    name: "Wonka's Dream",
    category: "cocktail",
    price: 9.0,
    ingredients: [
      "Baileys",
      "Liquore al Pocket Coffee (home made)",
      "Crema di latte alcolica aromatizzata al cacao",
    ],
    chefRecommended: true,
  },
  {
    id: 2,
    name: "Purple Spritz",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Granatina", "Blu Curaçao", "Prosecco"],
    chefRecommended: true,
  },
  {
    id: 3,
    name: "Aviation",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Gin", "Maraschino", "Bitters di violetta", "Succo di lime"],
    chefRecommended: false,
  },
  {
    id: 4,
    name: "Krakaccino",
    category: "cocktail",
    price: 9.0,
    ingredients: ["Rum Kraken", "Baileys", "Caffè", "Sciroppo di zucchero"],
    chefRecommended: true,
  },
  {
    id: 5,
    name: "Punto ICS",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Pestato di lime",
      "Zucchero di canna",
      "Disaronno",
      "Jack Daniel's",
      "Coca Cola",
    ],
    chefRecommended: true,
  },
  {
    id: 6,
    name: "Paloma",
    category: "cocktail",
    price: 10.0,
    ingredients: ["Tequila Silver", "Succo di lime", "Tonica al pompelmo rosa"],
    chefRecommended: true,
  },
  {
    id: 7,
    name: "Mezcal Paloma",
    category: "cocktail",
    price: 13.0,
    ingredients: [
      "Mezcal Montelobos",
      "Succo di lime",
      "Tonica al pompelmo rosa",
    ],
    chefRecommended: true,
  },
  {
    id: 8,
    name: "Aperol Spritz",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Aperol", "Prosecco", "Soda"],
    chefRecommended: false,
  },
  {
    id: 9,
    name: "Aperol Orange",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Aperol", "Succo d'arancia"],
    chefRecommended: false,
  },
  {
    id: 10,
    name: "Americano",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Campari", "Vermouth rosso", "Soda"],
    chefRecommended: false,
  },
  {
    id: 11,
    name: "Bellini",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Purea di pesca", "Prosecco"],
    chefRecommended: false,
  },
  {
    id: 12,
    name: "Blow Job",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Disaronno", "Baileys", "Crema di latte"],
    chefRecommended: false,
  },
  {
    id: 13,
    name: "Bronx",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Gin", "Vermouth rosso", "Martini Dry", "Succo d'arancia"],
    chefRecommended: false,
  },
  {
    id: 14,
    name: "Brandy Alexander",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Cognac", "Crème de cacao scura", "Crema di latte"],
    chefRecommended: false,
  },
  {
    id: 15,
    name: "Black Russian",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Vodka", "Kahlùa"],
    chefRecommended: false,
  },
  {
    id: 16,
    name: "Martini Spritz",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Martini Bianco", "Prosecco"],
    chefRecommended: false,
  },
  {
    id: 17,
    name: "Mimosa",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Prosecco", "Succo d'arancia"],
    chefRecommended: false,
  },
  {
    id: 18,
    name: "Mojito",
    category: "cocktail",
    price: 8.0,
    ingredients: [
      "Ron Havana 3",
      "Pestato di lime",
      "Zucchero di canna",
      "Menta",
      "Soda",
    ],
    chefRecommended: false,
  },
  {
    id: 19,
    name: "Campari Spritz",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Campari", "Prosecco"],
    chefRecommended: false,
  },
  {
    id: 20,
    name: "Moscow Mule",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Vodka", "Succo di lime", "Ginger beer"],
    chefRecommended: false,
  },
  {
    id: 21,
    name: "Caipirinha",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Cachaça", "Pestato di lime", "Zucchero di canna"],
    chefRecommended: false,
  },
  {
    id: 22,
    name: "Manhattan",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Rye whiskey", "Vermouth rosso", "Angostura"],
    chefRecommended: false,
  },
  {
    id: 23,
    name: "Margarita",
    category: "cocktail",
    price: 8.0,
    ingredients: ["Tequila", "Triple sec", "Succo di lime"],
    chefRecommended: false,
  },
  {
    id: 24,
    name: "Martini Dry",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Vermouth dry", "Gin"],
    chefRecommended: false,
  },
  {
    id: 25,
    name: "Martini Perfect",
    category: "cocktail",
    price: 9.0,
    ingredients: ["Gin", "Vermouth dry", "Vermouth rosso"],
    chefRecommended: false,
  },
  {
    id: 26,
    name: "Mojito Passion Fruit",
    category: "cocktail",
    price: 8.0,
    ingredients: [
      "Ron Havana 3",
      "Pestato di lime",
      "Zucchero di canna",
      "Frutto della passione",
      "Menta",
      "Soda",
    ],
    chefRecommended: false,
  },
  {
    id: 27,
    name: "Caipiroska",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Pestato di lime",
      "Zucchero di canna",
      "Versione fruttata (pestato di frutta)",
    ],
    chefRecommended: false,
  },
  {
    id: 28,
    name: "Midori Melon Ball",
    category: "cocktail",
    price: 8.0,
    ingredients: ["Vodka", "Midori", "Succo d'arancia"],
    chefRecommended: false,
  },
  {
    id: 29,
    name: "Negroni",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Campari", "Vermouth rosso", "Gin"],
    chefRecommended: false,
  },
  {
    id: 30,
    name: "Negroni Sbagliato",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Campari", "Vermouth rosso", "Prosecco"],
    chefRecommended: false,
  },
  {
    id: 31,
    name: "Negroski",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Campari", "Vermouth rosso", "Vodka"],
    chefRecommended: false,
  },
  {
    id: 32,
    name: "Boulevardier",
    category: "cocktail",
    price: 9.0,
    ingredients: ["Campari", "Vermouth rosso", "Scotch whiskey", "Angostura"],
    chefRecommended: true,
  },
  {
    id: 33,
    name: "Orgasm",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Cointreau", "Baileys", "Grand Marnier", "Crema di latte"],
    chefRecommended: false,
  },
  {
    id: 34,
    name: "Old Fashioned",
    category: "cocktail",
    price: 8.0,
    ingredients: [
      "Bourbon whiskey",
      "Zolletta di zucchero",
      "Angostura",
      "Soda",
    ],
    chefRecommended: false,
  },
  {
    id: 35,
    name: "Cosmopolitan",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Vodka", "Cointreau", "Succo di lime", "Succo di cranberry"],
    chefRecommended: false,
  },
  {
    id: 36,
    name: "Passion Cocktail",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Vodka alla pesca", "Passoa", "Succo d'ananas"],
    chefRecommended: false,
  },
  {
    id: 37,
    name: "Planter's Punch",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Ron Havana 3",
      "Angostura",
      "Succo d'arancia",
      "Succo d'ananas",
      "Succo di limone",
      "Granatina",
      "Sciroppo di zucchero",
    ],
    chefRecommended: false,
  },
  {
    id: 38,
    name: "Rusty Nail",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Scotch whiskey", "Drambuie"],
    chefRecommended: false,
  },
  {
    id: 39,
    name: "Cuba Libre",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Ron Havana 3", "Succo di lime", "Coca Cola"],
    chefRecommended: false,
  },
  {
    id: 40,
    name: "Sea-Breeze",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Vodka", "Succo di mirtilli", "Succo di pompelmo"],
    chefRecommended: false,
  },
  {
    id: 41,
    name: "Screwdriver",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Vodka", "Succo d'arancia"],
    chefRecommended: false,
  },
  {
    id: 42,
    name: "Mai Tai",
    category: "cocktail",
    price: 8.0,
    ingredients: [
      "Ron Havana 3",
      "Rum Años 7",
      "Orange Curaçao",
      "Sciroppo di orzata",
      "Succo di lime",
    ],
    chefRecommended: false,
  },
  {
    id: 43,
    name: "Sex on the Beach",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Peach Three",
      "Succo di mirtillo",
      "Succo d'arancia",
    ],
    chefRecommended: false,
  },
  {
    id: 44,
    name: "Daiquiri",
    category: "cocktail",
    price: 6.0,
    ingredients: ["Ron Havana 3", "Succo di limone", "Sciroppo di zucchero"],
    chefRecommended: false,
  },
  {
    id: 45,
    name: "Tequila Sunrise",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Tequila", "Granatina", "Succo d'arancia"],
    chefRecommended: false,
  },
  {
    id: 46,
    name: "God Father",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Scotch whiskey", "Disaronno"],
    chefRecommended: false,
  },
  {
    id: 47,
    name: "Violet",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Gin",
      "Rum",
      "Triple sec",
      "Blue Curaçao",
      "Granatina",
      "Lemon soda",
    ],
    chefRecommended: false,
  },
  {
    id: 48,
    name: "God Mother",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Vodka", "Disaronno"],
    chefRecommended: false,
  },
  {
    id: 49,
    name: "White Russian",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Vodka", "Kahlùa", "Crema di latte"],
    chefRecommended: false,
  },
  {
    id: 50,
    name: "Gix",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Malibu",
      "Purea di fragola",
      "Purea di banana",
      "Succo d'ananas",
    ],
    chefRecommended: false,
  },
  {
    id: 51,
    name: "Hotline",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Vodka", "Purea di passion fruit", "Carlo Alberto"],
    chefRecommended: true,
  },
  {
    id: 52,
    name: "Summer Wind",
    category: "cocktail",
    price: 8.0,
    ingredients: ["Gin Hendrick's", "Purea di mandarino", "Tonica"],
    chefRecommended: true,
  },
  {
    id: 53,
    name: "Japanese Ice Tea",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Gin",
      "Rum",
      "Midori",
      "Sweet and sour",
      "Lemon soda",
    ],
    chefRecommended: false,
  },
  {
    id: 54,
    name: "Hermano",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Cachaça",
      "Succo di limone",
      "Purea di papaya",
      "Passoa",
      "Soda",
    ],
    chefRecommended: false,
  },
  {
    id: 55,
    name: "Car Michael",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Triple sec",
      "Succo di lime",
      "Purea di ciliegia",
      "Sprite",
    ],
    chefRecommended: false,
  },
  {
    id: 56,
    name: "Manda Mule",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Succo di lime",
      "Purea di mandarino",
      "Ginger beer",
    ],
    chefRecommended: false,
  },
  {
    id: 57,
    name: "Passion Mule",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Succo di lime",
      "Purea di passion fruit",
      "Ginger beer",
    ],
    chefRecommended: false,
  },
  {
    id: 58,
    name: "Japanese Slipper",
    category: "cocktail",
    price: 8.0,
    ingredients: ["Midori", "Cointreau", "Succo di limone"],
    chefRecommended: false,
  },
  {
    id: 59,
    name: "Àdios",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Gin",
      "Ron havana 3",
      "Tequila",
      "Blue Curaçao",
      "Sciroppo di zucchero",
      "Sprite",
    ],
    chefRecommended: false,
  },

  {
    id: 60,
    name: "Puffo",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Ron Havana 3",
      "Gin",
      "Blue Curaçao",
      "Zucchero di canna",
      "Lemon soda",
    ],
    chefRecommended: false,
  },
  {
    id: 61,
    name: "Mojitini",
    category: "cocktail",
    price: 8.0,
    ingredients: [
      "Vodka Zubrowka",
      "Birra lager",
      "Menta",
      "Zucchero di canna",
      "Pestato di lime",
    ],
    chefRecommended: true,
  },
  {
    id: 62,
    name: "John Collins",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Gin",
      "Succo di limone",
      "Sciroppo di zucchero",
      "Angostura",
      "Soda",
    ],
    chefRecommended: false,
  },
  {
    id: 63,
    name: "Limoncelletto",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Vodka", "Crema di limoncello", "Granatina", "Red Bull"],
    chefRecommended: false,
  },
  {
    id: 64,
    name: "Flirt",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Gin",
      "Triple sec",
      "Purea di mango",
      "Ginger beer",
    ],
    chefRecommended: false,
  },
  {
    id: 65,
    name: "Sharm",
    category: "cocktail",
    price: 9.0,
    ingredients: [
      "Gin della Madame",
      "Acqua di rose",
      "Aroma di gelsomino",
      "Ginger ale",
    ],
    chefRecommended: true,
  },
  {
    id: 66,
    name: "Fox",
    category: "cocktail",
    price: 8.0,
    ingredients: [
      "Vodka",
      "Tabasco",
      "Succo di limone",
      "Angostura",
      "Grimbergen Double",
    ],
    chefRecommended: false,
  },
  {
    id: 67,
    name: "Kamikaze",
    category: "cocktail",
    price: 7.0,
    ingredients: ["Vodka", "Cointreau", "Succo di lime"],
    chefRecommended: false,
  },
  {
    id: 68,
    name: "Monte Mule",
    category: "cocktail",
    price: 8.0,
    ingredients: ["Montenegro", "Succo di lime", "Ginger beer"],
    chefRecommended: false,
  },
  {
    id: 69,
    name: "Il 130",
    category: "cocktail",
    price: 8.0,
    ingredients: ["Montenegro", "Pestato di lime", "Zucchero di canna", "Soda"],
    chefRecommended: false,
  },
  {
    id: 70,
    name: "Capo Sour",
    category: "cocktail",
    price: 9.0,
    ingredients: ["Amaro del Capo", "Sweet and sour", "Soda"],
    chefRecommended: false,
  },
  {
    id: 71,
    name: "Long Island Ice Tea",
    category: "cocktail",
    price: 7.0,
    ingredients: [
      "Vodka",
      "Gin",
      "Triple sec",
      "Rum",
      "Sweet and sour",
      "Coca Cola",
    ],
    chefRecommended: false,
  },
];
